### ISSUE TITLE
Dolphin doesn't detect device

### ISSUE THREAD

**Issue by WodsonKun** [marcowindt/WiiMoteDSU#1] opened 2020-08-13 23:09 UTC
I've built your application and tried to run it with Dolphin
And I don't know why, but Dolphin doesn't detect my phone
(And yes, i've tried to use your configuration file too, and didn't worked as well)

**Comment by marcowindt** [comment] 2020-08-17 18:25
I wasn't expecting someone to be actually interested in this application, therefore the install notes are still TODO 😅, but I will add them.

Did you enable the DSU Client within Dolphin under "Controller Settings" > "Alternate Input Sources"? (see screenshot)

<img width="500" alt="Schermafbeelding 2020-08-17 om 20 17 59" src="https://user-images.githubusercontent.com/9336858/90430180-47722c80-e0c7-11ea-9de3-cb60e62606d0.png">

**Comment by WodsonKun** [comment] 2020-08-18 12:06
> I wasn't expecting someone to be actually interested in this application, therefore the install notes are still TODO 😅, but I will add them.

Man, your project is the only DSU server for Android with input... Of course I was interested :)

> Did you enable the DSU Client within Dolphin under "Controller Settings" > "Alternate Input Sources"? (see screenshot)

Yup, everything
Even tried with Ishiiiruka-UDP

**Comment by WodsonKun** [comment] 2020-08-18 14:22
Ok, now I rebuilt it with your install notes and it works now
Thanks for your help!

**Comment by WodsonKun** [comment] 2020-08-18 14:28
One more problem: Gryoscope
When using MotionSource, it works nicely

But when using WiiMoteDSU, it "goes loco"
I don't know why

**Comment by WodsonKun** [comment] 2020-08-18 14:38
Using WiiMoteDSU: https://youtu.be/AN36HfTqHcY
Using MotionSource: https://youtu.be/gZ8cMdpTfRc

**Comment by WodsonKun** [comment] 2020-08-18 14:58
![image](https://user-images.githubusercontent.com/22161127/90529409-11c25780-e14a-11ea-882d-06385e8c9355.png)
Testing it with other games, I had two responses

Going loco or wiimote acting as it was inversed

**Comment by marcowindt** [comment] 2020-08-19 08:46
>Man, your project is the only DSU server for Android with input... Of course I was interested :)

That is indeed the reason why I made it in the first place.

>One more problem: Gryoscope
>When using MotionSource, it works nicely
>
>But when using WiiMoteDSU, it "goes loco"

I knew this problem existed, but I stopped working on the motion input when I was able to register a shake when playing Mario 😅

The problem is that Dolphin uses the accelerometer as input for the pointer when available, therefore I now disabled the accelerometer by default, but added a simple settings screen to be able to invert the axes of the accelerometer/gyroscope and enabled/disable the accelerometer input (see screenshot in README).

Motion input still isn't perfect, but should be better now.

**Comment by WodsonKun** [comment] 2020-08-19 15:28
Yeah, i've rebuilt and it's working properly now
Besides that now, the cursor goes to left or right by tilting the phone, not moving it (as in MotionSource or in the older version of WiiMoteDSU)

But it sure works now
Thanks for helping me out ❤

**Comment by marcowindt** [comment] 2020-08-19 16:16
Glad it helped!

When I find time I will make it more configurable, e.g. to be able to adjust the input to the device orientation, like the iOS app [MotionSourceiOS](https://github.com/shiftinv/MotionSourceiOS).

Apparently the MotionSource app for Android is not open source, or at least I couldn't find it.

Will close this issue.

**Closed as completed** 2020-08-19 16:16 UTC

**Comment by Abrifq** [comment] 2020-10-02 18:41
Hi, I'm having similar issues and my problem is that "IP address" field is never filled up.

For building the app, I followed the README (so I don't know if there is a special installation notes) and made a github ci for it on my fork. I'm using android 10 (api level 29), idk if that changes anything or not.
