### ISSUE TITLE
using dev version, buttons are only being mapped if you press it multiple times

### ISSUE THREAD

**Issue by thondorigithub1** [marcowindt/WiiMoteDSU#74] opened 2023-01-22 09:54 UTC

**Comment by marcowindt** [comment] 2023-01-25 18:25
Should be fixed in [new pre-release version](https://github.com/marcowindt/WiiMoteDSU/releases/tag/v0.3.0-develop.2).

**Comment by marcowindt** [comment] 2023-01-26 21:16
Closing this, a fix for the issue is available in [v0.3.0](https://github.com/marcowindt/WiiMoteDSU/releases/tag/v0.3.0). Feel free to re-open this issue or open a new issue when you encounter any problems with mapping buttons.

**Closed as completed by marcowindt** 2023-01-26 21:16 UTC
